Repository boostcampwm-2021/WEB19-sajagachi, pull requests merged in 2021-11, with the labels that each got.

#14 feat[#11] : gnb 검색바 ui 변경
  client/src/common/gnb/component/SearchInput.tsx
  client/src/common/gnb/index.tsx
Labels: frontend, feat

#16 feat[#11] : gnb 검색바 ui 변경
  client/src/common/gnb/component/SearchInput.tsx
Labels: frontend, feat

#17 feat[#13] : gnb 렌더링시 현재 위치 받아오기
  client/src/common/gnb/index.tsx
Labels: frontend, feat

#20 feat : post list UI 작성 - close #18
  client/src/App.tsx
  client/src/common/post-list/component/Item.tsx
  client/src/common/post-list/index.tsx
  client/src/common/tag/index.tsx
  client/src/type/types.ts
Labels: frontend, feat

#22 feat[#21] : Entity 생성
  server/model/entity/Category.ts
  server/model/entity/Chat.ts
  server/model/entity/Participant.ts
  server/model/entity/Post.ts
  server/model/entity/Url.ts
  server/model/entity/User.ts
  server/model/entity/WishList.ts
  server/routes/index.ts
  server/routes/post.ts
Labels: backend, feat

#25 Feat/#23 : GET /post API 구현
  server/controller/post-controller.ts
  server/routes/post.ts
  server/service/participant-service.ts
  server/service/post-service.ts
  server/type/index.ts
Labels: backend, feat

#27 feat[#26] : 메인 페이지 글쓰기 FAB 추가 - close #26
  client/src/App.tsx
  client/src/common/post-list/index.tsx
  client/src/page/main/component/FAB.tsx
  client/src/page/main/index.tsx
Labels: frontend, feat

#29 feat[#28] : post api error 처리 - close #28
  server/controller/post-controller.ts
  server/routes/post.ts
  server/service/post-service.ts
Labels: backend, feat

#35 feat[#30] : Fetch 유틸리티 함수 및 CORS
  client/src/util/util.ts
  server/app.ts
  server/package-lock.json
  server/package.json
Labels: backend, frontend, feat

#41 Feat[#36] : 게시판 데이터 불러오기 구현
  client/package-lock.json
  client/package.json
  client/src/common/post-list/component/Item.tsx
  client/src/common/post-list/index.tsx
  client/src/page/main/index.tsx
  client/src/type/types.ts
  client/src/util/util.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#43 feat[#39] : recoil을 통한 현재 위치 저장
  client/package-lock.json
  client/package.json
  client/src/common/gnb/index.tsx
  client/src/index.tsx
  client/src/page/main/component/FilteringModal.tsx
  client/src/page/main/component/MapModal.tsx
  client/src/page/main/component/NaverMapAPI.tsx
  client/src/store/loction.ts
Labels: frontend, feat

#44 feat[#42] : API 호출 path 변경 및 Alert 컴포넌트 추가 - close #42
  client/src/page/main/index.tsx
  client/src/util/util.ts
  server/app.ts
Labels: backend, frontend, feat

#46 feat[#45] : 게시판 리스트 Fetch 예외 처리
  client/src/asset/noitem.png
  client/src/common/post-list/index.tsx
  client/src/page/main/component/FAB.tsx
  client/src/page/main/index.tsx
Labels: frontend, feat

#48 fix[#47] : github action 백엔드 배포 버그 수정
  .github/workflows/deploy.yml
Labels: fix

#52 feat[#51] : 지도 drawer 적용 및 버그 수정
  client/src/page/main/component/FilteringModal.tsx
  client/src/page/main/component/MapDrawer.tsx
  client/src/page/main/component/MapModal.tsx
  client/src/page/main/component/NaverMapAPI.tsx
Labels: frontend, feat, fix

#53 fix[#50] : 메인페이지 게시글 fetch 이후 발생 bug fix - close #50
  client/src/common/gnb/index.tsx
  client/src/common/post-list/index.tsx
  client/src/page/main/component/ErrorAlert.tsx
  client/src/page/main/index.tsx
Labels: bug, frontend

#57 feat[#54] : 필터링 모달 뷰 수정
  client/src/common/post-list/component/Item.tsx
  client/src/common/tag/index.tsx
  client/src/page/main/component/FilteringModal.tsx
  client/src/type/types.ts
Labels: frontend, feat

#59 Feat/#53 무한 스크롤 구현
  client/src/common/post-list/index.tsx
  client/src/page/main/index.tsx
Labels: frontend, feat

#60 Feat/#58 - 필터 관련 API 수정, 쿼리스트링 생성
  client/src/common/gnb/index.tsx
  client/src/common/post-list/component/Item.tsx
  client/src/common/post-list/index.tsx
  client/src/page/main/component/FilteringModal.tsx
  client/src/page/main/index.tsx
  client/src/store/location.ts
  client/src/store/loction.ts
  client/src/type/index.ts
  client/src/type/types.ts
  client/src/util/util.ts
  server/service/post-service.ts
  server/type/index.ts
Labels: backend, frontend, feat

#66 fix[#65] : SearchModal 옵션 클릭 Bugfix - close #65
  client/src/common/search-modal/index.tsx
Labels: bug, frontend

#68 Feat/#63 네이버 지도 API를 통해 도로명 주소를 필터링 검색창에 출력
  client/public/index.html
  client/src/common/gnb/index.tsx
  client/src/common/search-modal/component/FilteringModal.tsx
  client/src/common/search-modal/component/MapDrawer.tsx
  client/src/common/search-modal/component/NaverMapAPI.tsx
  client/src/common/search-modal/index.tsx
  client/src/store/location.ts
Labels: frontend, feat

#75 feat[#73] : query string에 따라 필터의 상태 유지 - close #73
  client/src/common/search-modal/index.tsx
  client/src/type/index.ts
  client/src/util/util.ts
Labels: frontend, feat

#77 Feat[#76] : 서버에서 카테고리 리스트 받아오기
  client/src/common/search-modal/index.tsx
  client/src/util/util.ts
  server/controller/category-controller.ts
  server/controller/post-controller.ts
  server/routes/category.ts
  server/routes/index.ts
  server/service/category-service.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#82 feat[#81] : 위도, 경도에 따라 게시글 필터링 기능 추가
  server/service/post-service.ts
  server/type/index.ts
Labels: backend, feat

#86 게시글 상세 페이지 북마크 출력
  client/src/page/detail/component/LinkPreview.tsx
  client/src/page/detail/index.tsx
  server/package-lock.json
  server/package.json
  server/service/post-service.ts
Labels: backend, frontend, feat

#88 refactor[#87] : 게시글 상세페이지에서 안쓰는 변수 삭제
  client/src/page/detail/component/LinkPreview.tsx
  client/src/page/detail/index.tsx
Labels: frontend

#89 [Feat/#72] 작성 페이지 모달 ui 구성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/page/main/component/FAB.tsx
  client/src/page/main/index.tsx
  client/src/page/post/component/CheckCategory.tsx
  client/src/page/post/component/DateDeadline.tsx
  client/src/page/post/component/InputContent.tsx
  client/src/page/post/component/InputTitle.tsx
  client/src/page/post/component/InputUrl.tsx
  client/src/page/post/component/SelectCapacity.tsx
  client/src/page/post/index.tsx
Labels: frontend, feat

#93 [Fix/#90] 카테고리 한개만 선택 가능하도록 수정
  client/src/page/post/component/CheckCategory.tsx
  client/src/page/post/index.tsx
Labels: frontend, fix

#96 feat[#92] : mui에 폰트 적용 - close #92
  client/src/App.tsx
Labels: frontend

#97 feat[#94] : 제목, 내용, 카테고리 미 입력시 등록 버튼 비활성화
  client/src/page/post/component/CheckCategory.tsx
  client/src/page/post/index.tsx
Labels: frontend, feat

#100 Feat/#84 : 게시글 리스트 api 최적화
  server/model/entity/Post.ts
  server/service/post-service.ts
Labels: backend, feat

#105 feat[#104] : SSE 통신으로 상세 페이지 마감시간 구현
  client/public/index.html
  client/src/page/detail/index.tsx
  server/app.ts
  server/routes/sse.ts
Labels: backend, frontend, feat

#108 [feat/#95] 백엔드 api 생성 및 등록 버튼 클릭시 api 호출 & 데이터베이스 스키마 변경
  client/src/page/post/index.tsx
  client/src/util/util.ts
  server/controller/post-controller.ts
  server/model/entity/Chat.ts
  server/model/entity/Participant.ts
  server/model/entity/Url.ts
  server/ormconfig.js
  server/routes/post.ts
  server/service/post-service.ts
  server/type/index.ts
Labels: backend, frontend, feat

#109 상세 페이지 마감시간 리팩토링
  client/src/page/detail/component/DeadLine.tsx
  client/src/page/detail/index.tsx
Labels: frontend, refactor

#112 feat[#111] : 완료 버튼 왼쪽에 취소 버튼 생성
  client/src/common/search-modal/index.tsx
Labels: frontend, feat

#115 fix[#114]: 인원 선택 안했을 시에 0이 아닌 null이 저장되도록 변경
  server/service/post-service.ts
Labels: backend, fix

#116 feat[#110] : GNB 로고 수정 및 뒤로가기 버튼 배치
  client/src/asset/logo1.svg
  client/src/asset/logo2.svg
  client/src/asset/logo3.svg
  client/src/common/gnb/component/BackButton.tsx
  client/src/common/gnb/component/SearchModalDrawer.tsx
  client/src/common/gnb/index.tsx
Labels: frontend

#118 로그인 모달창 구현
  client/src/asset/Gugi-Regular.ttf
  client/src/asset/github.svg
  client/src/common/gnb/index.tsx
  client/src/common/login-modal/index.tsx
  client/src/style.css
Labels: frontend, feat

#124 fix[#123] : 메인 페이지 게시글 Description 잘림 현상 해결 - close #123
  client/src/common/post-list/component/Item.tsx
Labels: frontend, fix

#129 채팅페이지 UI 레이아웃 완료
  client/src/App.tsx
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/chat/index.tsx
Labels: frontend, feat

#132 feat[#126] : 게시글 리스트 뷰 개선 작업
  client/src/common/post-list/component/Item.tsx
  client/src/common/post-list/component/ItemContent.tsx
  client/src/type/index.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#135 feat[#134] : 채팅 페이지 메뉴 레이아웃 구현
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/component/UserList.tsx
Labels: frontend, feat

#136 Feat/#131 - JWT를 이용한 임시 로그인 구현
  client/src/common/login-modal/index.tsx
  client/src/util/util.ts
  server/app.ts
  server/controller/login-controller.ts
  server/model/entity/User.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/routes/login.ts
  server/service/login-service.ts
  server/type/index.ts
Labels: backend, feat

#138 Feat[#130] : 상세페이지에서 채팅 참여 기능 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/index.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/index.tsx
  server/app.ts
  server/controller/participant-controller.ts
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/routes/participant.ts
  server/service/participant-service.ts
  server/service/post-service.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#140 Feat[#91] : link-preview 구현
  client/src/page/detail/component/LinkPreview.tsx
  client/src/page/detail/index.tsx
  server/controller/linkPreview-controller.ts
  server/package-lock.json
  server/package.json
  server/routes/index.ts
  server/routes/linkPreview.ts
  server/service/linkPreview-service.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#142 refactor[#141] - 채팅페이지 UI 리팩토링
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  server/package-lock.json
Labels: refactor

#146 Refactor/#145
  client/src/page/detail/component/GroupBuyButton.tsx
  server/controller/participant-controller.ts
  server/routes/chat.ts
  server/routes/index.ts
  server/service/participant-service.ts
  server/service/post-service.ts
Labels: backend, refactor

#147 refactor[#143] : 게시글 리스트 부분 리팩토링
  client/src/common/post-list/component/ItemContent.tsx
Labels: frontend, fix

#139 feat[#137] : 채팅 페이지 참여자 리스트 개선
  client/src/asset/crown.svg
  client/src/page/chat/component/UserList.tsx
Labels: frontend, feat

#151 feat[#148] : 채팅 참여자 리스트 서버 연동 작업
  client/src/common/confirm/index.tsx
  client/src/page/chat/component/UserList.tsx
  server/controller/participant-controller.ts
  server/routes/chat.ts
  server/service/participant-service.ts
Labels: backend, frontend, feat

#153 feat[#152] : GNB의 서비스 로고 하나로 고정
  client/src/asset/logo.svg
  client/src/asset/logo1.svg
  client/src/asset/logo3.svg
  client/src/common/gnb/index.tsx
Labels: frontend, feat

#155 fix[#154] : 상세 페이지 참여 인원 NULL 출력 버그 & 공동 구매 참여 버튼 비활성화 버그 수정
  client/src/page/detail/component/GroupBuyButton.tsx
  server/package-lock.json
Labels: frontend, fix

#157 Feat[#149] : socket.io 를 이용하여 채팅 구현
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/index.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/index.tsx
  server/controller/participant-controller.ts
  server/controller/post-controller.ts
  server/service/participant-service.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#159 fix[#156] : meta viewport 수정
  client/public/index.html
Labels: bug, frontend

#160 Feat/#158
  client/src/page/chat/index.tsx
  client/src/util/util.ts
  server/service/chat-service.ts
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#163 fix[#119] : 현재 위치 관련 버그 해결
  client/src/common/search-modal/component/NaverMapAPI.tsx
  client/src/common/search-modal/index.tsx
  client/src/page/main/index.tsx
  client/src/type/index.ts
  client/src/util/util.ts
Labels: frontend, fix

#165 포인트 입력 후 확정 및 취소 버튼 누르면 데이터베이스 업데이트
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/index.tsx
  server/controller/login-controller.ts
  server/model/entity/Participant.ts
  server/service/participant-service.ts
  server/service/user-service.ts
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#166 feat[#164] : 현재 위치 로딩 화면 구현 및 위치 로딩 실패시 모달 출력
  client/src/asset/loading.gif
  client/src/common/alert/index.tsx
  client/src/common/gnb/component/LoadingUI.tsx
  client/src/common/gnb/index.tsx
  client/src/page/main/index.tsx
  client/src/store/location.ts
  client/src/type/index.ts
Labels: frontend, feat

#169 Feat[#162] : 채팅 받을 시 스크롤 위치 변경
  client/src/page/chat/index.tsx
Labels: frontend, feat

#171 fix[#170] : 11월 16일자 작업에 대한 리팩토링
  client/src/common/search-modal/index.tsx
  client/src/index.tsx
  client/src/page/chat/component/UserList.tsx
  client/src/page/detail/index.tsx
  client/src/page/main/index.tsx
Labels: frontend, fix

#173 로그인 정보 리코일을 이용해 전역으로 관리
  client/src/common/login-modal/index.tsx
  client/src/page/post/index.tsx
  client/src/store/login.ts
  client/src/type/index.ts
  server/controller/login-controller.ts
Labels: frontend, feat

#175 linkPreview-controller 리팩토링
  server/controller/linkPreview-controller.ts
  server/type/index.ts
Labels: refactor

#178 bug[#176] : 상세 페이지 마감 기한 null 버그 fix
  client/src/page/detail/index.tsx
Labels: bug

#179 채팅 메뉴 켰을 때 현재 구매 상태에 따라 다르게 표시
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/index.tsx
  client/src/util/util.ts
  server/controller/login-controller.ts
  server/controller/participant-controller.ts
  server/routes/chat.ts
  server/service/user-service.ts
  server/socket/chat.ts
Labels: backend, frontend, feat

#180 feat[#172] : 현재 위치 정보 캐싱 및 메인 페이지에 위치 관련 인터페이스 추가
  client/src/common/gnb/index.tsx
  client/src/common/post-list/index.tsx
  client/src/common/search-modal/index.tsx
  client/src/page/main/component/LocationIndicator.tsx
  client/src/page/main/index.tsx
  client/src/util/util.ts
Labels: frontend, feat

#182 post 작성시 참여자에 자동으로 참가하도록 변경
  server/controller/post-controller.ts
  server/service/post-service.ts
Labels: backend, fix

#185 feat[#184] : 채팅 메뉴에서 참여자 리스트 출력하기
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/UserList.tsx
  server/controller/post-controller.ts
  server/routes/post.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#187 style[#177] : 채팅 페이지 스타일 변경
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/chat/index.tsx
Labels: frontend, refactor

#189 feat[#186] : 게시글 리스트에서 거리 정보를 포함
  client/src/common/post-list/component/ItemContent.tsx
  client/src/type/index.ts
  client/src/util/util.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#193 feat[#192] : react-cookie 모듈사용해서 쿠키 접근
  client/package-lock.json
  client/package.json
  client/src/util/cookie.ts
  server/controller/login-controller.ts
Labels: frontend, feat

#198 로그인 완료시 현재 페이지 새로고침
  client/src/common/login-modal/index.tsx
Labels: frontend, fix

#199 feat[#196] : 채팅페이지에서 participants 받아오기
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/index.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/type/index.ts
Labels: frontend, feat

#202 로그인 시 새로고침 되지 않고 현재페이지를 유지하도록 변경
  client/src/common/login-modal/index.tsx
Labels: frontend, fix

#203 feat[#194] : 사용자 내보내기 기능 구현
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/UserList.tsx
  client/src/page/chat/index.tsx
  client/src/util/cookie.ts
  server/service/participant-service.ts
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#205 포인트 제출시 참여자 목록 포인트 부분 업데이트
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/index.tsx
  client/src/type/index.ts
  server/controller/participant-controller.ts
  server/controller/user-controller.ts
  server/routes/chat.ts
  server/routes/index.ts
  server/routes/user.ts
Labels: backend, frontend, feat

#206 Feat/#191 스크롤시 채팅 내역 출력 기능 구현
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/index.tsx
  client/src/type/index.ts
  server/controller/chat-controller.ts
  server/routes/chat.ts
  server/service/chat-service.ts
Labels: backend, frontend, feat

#209 Feat[#200] : 채팅내용 머지 완료
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/index.tsx
  client/src/type/index.ts
  server/service/chat-service.ts
Labels: backend, frontend, feat

#211 feat[#204] : 채팅방 나가기 기능 구현 (호스트가 아닌 참여자)
  client/src/page/chat/component/ChatMenu.tsx
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#213 호스트를 제외한 모든 참여자가 구매를 확정하면 호스트 화면에서 포인트 회수 버튼 활성화
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/HostPointView.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/post/index.tsx
  server/controller/post-controller.ts
  server/routes/post.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#218 페이지 마다 렌더링시 전역 상태로 로그인 정보 확인하고 없으면 jwt로 불러오기
  client/src/common/login-modal/index.tsx
  client/src/page/chat/component/UserList.tsx
  client/src/page/chat/index.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/index.tsx
  client/src/page/main/component/FAB.tsx
  client/src/page/main/index.tsx
  client/src/page/post/index.tsx
  server/controller/login-controller.ts
Labels: backend, frontend, feat

#215 처음 화면에 메뉴 렌더링시 종료여부를 확인하지 않던 버그 수정
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/HostPointView.tsx
Labels: frontend, fix

#221 feat[#220] : 사용자 방 입장시 실시간 업데이트 및 채팅방 나가기 후 뒤로가기 문제 해결
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/index.tsx
  server/socket/chat.ts
Labels: backend, frontend, feat

#228 feat[#208] : 채팅 보낼시 cookie를 같이보내 서버에서 유저 확인
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/ChatList.tsx
  server/controller/chat-controller.ts
  server/controller/login-controller.ts
  server/service/chat-service.ts
  server/socket/chat.ts
Labels: backend, frontend, feat

#230 fix[#229] : 채팅참여 인원이 꽉 찼을 때 상세페이지 문제 해결 - close
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/index.tsx
  server/controller/post-controller.ts
  server/service/participant-service.ts
  server/socket/chat.ts
  server/util/index.ts
Labels: backend, frontend, fix

#236 fix[#234] : 로그인 되어있지 않는 user 상세페이지 입장 관련 오류 해결
  server/controller/post-controller.ts
Labels: backend, fix

#235 + 버튼을 누르면 이미지를 업로드 할 수 있도록 구현
  client/package-lock.json
  client/package.json
  client/src/page/chat/component/ChatInput.tsx
Labels: frontend, feat

#238 fix[#237] - 채팅페이지 12시 관련 오류 해결
  client/src/util/index.ts
Labels: frontend, fix

#243 fix[#240] : safari에서 채팅 좌,우 반영안되는 오류 해결
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
Labels: frontend, fix

#245 feat[#244] : 채팅방 강제 퇴장을 당한 클라이언트에서 페이지 이동 처리
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/index.tsx
  server/socket/chat.ts
Labels: backend, frontend, feat

#232 client에서 받은 image를 저장
  server/.gitignore
  server/app.ts
  server/controller/chat-controller.ts
  server/package-lock.json
  server/package.json
  server/routes/chat.ts
Labels: backend, feat

#248 feat[#246] : 참여자 리스트 스크롤 구현
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/HostPointView.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/component/UserList.tsx
Labels: frontend, feat

#251 채팅 페이지 소켓 이벤트 시스템 메시지로 출력
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/chat/component/SystemMessage.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  server/controller/participant-controller.ts
  server/socket/chat.ts
Labels: backend, frontend, feat

#252 fix[#247] : 기존의 이미지 업로드 axios 사용하던 것 fetch api로 수정
  client/package.json
  client/src/page/chat/component/ChatInput.tsx
  client/src/util/index.ts
Labels: frontend, fix

#254 fix[#250] : 모집 종료되어도 공구 참여중이라면 채팅방에서 이동할 수 있음 - close
  client/src/page/detail/component/GroupBuyButton.tsx
Labels: frontend, fix

#255 LinkPreview 존재하지 않는 url일 경우 오류 처리
  client/package-lock.json
  client/src/page/detail/component/LinkPreview.tsx
Labels: frontend, fix

#256 feat[#249] : 채팅방을 나가지 못하는 경우에 대한 처리
  client/src/page/chat/component/ChatMenu.tsx
  server/socket/chat.ts
Labels: backend, frontend, feat

#258 호스트 채팅 메뉴에서 포인트를 가져오면 공구 종료 상태로 변경
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/FinishedPointView.tsx
  client/src/page/chat/component/HostPointView.tsx
  client/src/page/chat/component/PointView.tsx
  server/ormconfig.js
  server/service/participant-service.ts
  server/service/post-service.ts
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, frontend, feat

#261 종료되었을 때 나타나는 메뉴 화면 추가
  client/src/page/chat/component/FinishedPointView.tsx
Labels: frontend

#263 마감시간이 끝나도 공동 구매 참여할 수 있는 버그 수정
  client/src/page/detail/component/DeadLine.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/index.tsx
Labels: bug, frontend, fix

#264 feat[#260] : 마이 페이지 컴포넌트 추가
  client/src/App.tsx
  client/src/page/mypage/component/MyList.tsx
  client/src/page/mypage/component/Profile.tsx
  client/src/page/mypage/index.tsx
Labels: frontend, feat

#269 feat[#265] : 마이 페이지 및 Profile 컴포넌트 구현
  client/src/asset/footprint.png
  client/src/page/mypage/component/ChargePointModal.tsx
  client/src/page/mypage/component/Profile.tsx
  client/src/page/mypage/component/ReturnPointModal.tsx
  client/src/page/mypage/index.tsx
  server/controller/user-controller.ts
  server/routes/user.ts
Labels: backend, frontend, feat

#267 jwt에서 session으로 변경
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/HostPointView.tsx
  client/src/page/chat/component/PointView.tsx
  client/src/page/chat/component/UserList.tsx
  client/src/page/chat/index.tsx
  server/app.ts
  server/controller/login-controller.ts
  server/controller/participant-controller.ts
  server/package-lock.json
  server/package.json
  server/socket/chat.ts
  server/socket/index.ts
Labels: backend, feat

#272 feat[#270] : 로그인 상태에서 GNB 마이페이지 버튼 바꾸기
  client/src/common/gnb/index.tsx
Labels: frontend, feat

#275 상세페이지에서 참가 여부 확인시 jwt를 사용해서 로그인 정보를 받아오던 부분 수정
  server/controller/post-controller.ts
Labels: backend, fix

#266 Feat[#257] : 채팅페이지 이미지 보내기, 이미지 확대 기능 구현
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/component/ImageModal.tsx
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/chat/component/SystemMessage.tsx
  client/src/type/index.ts
  server/controller/chat-controller.ts
  server/routes/chat.ts
  server/service/chat-service.ts
  server/service/post-service.ts
  server/service/user-service.ts
  server/socket/chat.ts
Labels: backend, frontend, feat

#277 github oauth 로그인 구현
  client/src/common/login-modal/index.tsx
  server/controller/login-controller.ts
  server/package-lock.json
  server/package.json
  server/routes/login.ts
  server/service/user-service.ts
Labels: backend, frontend, feat

#279 모집 종료된 글이어도 색이 진하던 버그 수정
  client/src/common/post-list/component/ItemContent.tsx
Labels: frontend, fix

#282 feat[#280] : 로그아웃 기능 구현
  client/src/page/mypage/component/LogoutButton.tsx
  client/src/page/mypage/component/Profile.tsx
  server/controller/login-controller.ts
  server/routes/login.ts
Labels: backend, frontend, feat

#286 마이 페이지의 현재 참여한 게시글 리스트 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/common/loading-spinner/index.tsx
  client/src/page/mypage/component/MyList.tsx
  client/src/page/mypage/component/NoPosts.tsx
  server/controller/participant-controller.ts
  server/routes/user.ts
  server/service/participant-service.ts
Labels: backend, frontend, feat

#290 게시글 리스트에서 마감 여부 판단 조건 수정
  client/src/common/post-list/component/ItemContent.tsx
Labels: frontend, fix

#292 feat[#287] : 상세 페이지 UI 수정
  client/src/page/detail/index.tsx
  server/service/post-service.ts
Labels: backend, frontend, feat

#293 Feat[#285] : 채팅 페이지에서 상단에 제목을 출력
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/index.tsx
  server/controller/post-controller.ts
  server/routes/post.ts
  server/service/post-service.ts
Labels: backend, frontend, feat

#295 fix[#294] : 파일 저장 이름 양식 변경
  server/controller/chat-controller.ts
  server/package-lock.json
  server/package.json
Labels: backend, fix

#301 마감 날짜를 선택하면 선택한 다음 날짜의 00시로 저장되도록 변경
  client/src/page/post/index.tsx
  server/routes/category.ts
  server/routes/chat.ts
  server/routes/index.ts
  server/routes/linkPreview.ts
  server/routes/login.ts
  server/routes/post.ts
  server/routes/user.ts
Labels: backend, frontend, fix

#305 fix[#298] : 마이 페이지 스타일 관련 버그 수정
  client/src/common/post-list/component/Item.tsx
  client/src/page/mypage/component/ChargePointModal.tsx
  client/src/page/mypage/component/ReturnPointModal.tsx
Labels: frontend, fix

#306 메인 페이지의 게시글 리스트 api 요청에 SWR 적용
  client/src/hook/useMainInfinite.ts
  client/src/page/main/index.tsx
Labels: frontend, refactor

#309 Fix[#304] : 에러 관련 customhook 생성, 채팅페이지 리팩토링
  client/src/common/error-popper/index.tsx
  client/src/common/login/index.tsx
  client/src/hook/useError.tsx
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatInput.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/page/chat/index.tsx
  client/src/util/error-message.ts
  client/src/util/index.ts
  server/socket/chat.ts
Labels: frontend, fix, refactor

#308 로그인 체크 관련된 커스텀 훅 구현 및 리팩토링 적용
  client/src/hook/useLoginUser.ts
  client/src/page/detail/index.tsx
  client/src/page/main/index.tsx
  client/src/page/mypage/index.tsx
Labels: frontend, refactor

#318 게시글 작성페이지 제목, 내용을 useRef로 바꿔 리렌더링 방지 & 입력 안했을 시 popError
  client/src/page/post/component/InputContent.tsx
  client/src/page/post/component/InputTitle.tsx
  client/src/page/post/index.tsx
  client/src/type/index.ts
  client/src/util/error-message.ts
  client/src/util/service.ts
Labels: frontend, refactor

#320 fix[#315] : 이미지 교체 및 리사이즈
  client/src/asset/myPageNoList.gif
  client/src/page/mypage/component/NoParticipationList.tsx
Labels: frontend, fix

#322 상세 페이지 리팩토링
  client/src/page/detail/component/Bottom.tsx
  client/src/page/detail/component/Content.tsx
  client/src/page/detail/component/DeadLine.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/component/Header.tsx
  client/src/page/detail/index.tsx
  client/src/util/index.ts
  server/routes/sse.ts
Labels: frontend, refactor

#323 상세 페이지 리팩토링 v2
  client/src/page/detail/component/Bottom.tsx
  client/src/page/detail/component/Content.tsx
  client/src/page/detail/component/DeadLine.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/component/Header.tsx
  client/src/page/detail/index.tsx
Labels: frontend, refactor

#325 포인트 관련 작업 오류 발생시 에러 알림창
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/HostPointView.tsx
  client/src/page/chat/component/PointView.tsx
  server/socket/chat.ts
  server/util/error.ts
Labels: backend, frontend, feat

#328 fix[#324] : 채팅페이지 버그 수정
  client/src/page/chat/component/MyChatMessage.tsx
  client/src/page/chat/component/OtherChatMsg.tsx
  client/src/page/detail/component/GroupBuyButton.tsx
  server/controller/participant-controller.ts
  server/util/error.ts
Labels: frontend, fix

#329 refactor[#321] : 서치 모달 리팩토링
  client/src/common/search-modal/component/ButtonSet.tsx
  client/src/common/search-modal/component/FilterOption.tsx
  client/src/common/search-modal/component/Select.tsx
  client/src/common/search-modal/component/SelectChip.tsx
  client/src/common/search-modal/index.tsx
Labels: frontend, fix

#332 fix[#330] : 쿼리문 수정
  server/model/entity/Post.ts
  server/service/post-service.ts
Labels: backend, fix

#335 데이터베이스 여러번 접근시 queryRunner로 트랜잭션 원자성 유지 & 채팅 소켓 에러핸들링
  client/src/page/detail/component/GroupBuyButton.tsx
  client/src/page/detail/component/LinkPreview.tsx
  server/controller/chat-controller.ts
  server/controller/linkPreview-controller.ts
  server/controller/participant-controller.ts
  server/controller/post-controller.ts
  server/service/chat-service.ts
  server/socket/chat.ts
  server/util/error.ts
Labels: backend, frontend, fix

#338 feat[#337] : 에러 페이지 추가
  client/src/App.tsx
  client/src/asset/error.png
  client/src/page/error/index.tsx
  client/src/page/profile/index.tsx
Labels: frontend, feat

#341 feat[#340] : 에러페이지 적용 - close #340
  client/src/page/chat/index.tsx
  client/src/page/detail/index.tsx
  client/src/page/mypage/component/Profile.tsx
Labels: frontend, feat

#343 상세 페이지 카테고리 Chip의 디자인을 게시글 리스트와 동일하게 적용
  client/src/common/chip/CategoryChip.tsx
  client/src/common/chip/ParticipantChip.tsx
  client/src/common/chip/index.tsx
  client/src/common/post-list/component/ItemContent.tsx
  client/src/page/detail/component/Header.tsx
  client/src/util/index.ts
Labels: frontend, feat
