Repository boostcampwm-2021/WEB19-sajagachi, pull requests merged in 2021-12, with the labels that each got.

#345 채팅 소켓관련 에러 처리 및 off 추가
  client/src/page/chat/component/ChatList.tsx
  client/src/page/chat/component/ChatMenu.tsx
  client/src/page/chat/component/UserList.tsx
  client/src/page/chat/index.tsx
Labels: frontend, fix

#349 쿼리 최적화 결과 적용
  client/src/hook/useMainInfinite.ts
  client/src/page/main/index.tsx
  client/src/type/index.ts
  server/controller/post-controller.ts
  server/model/entity/Post.ts
  server/service/post-service.ts
  server/type/index.ts
Labels: backend, frontend, fix

#355 url 저장시 http 추가 및 데이터베이스 채팅 메시지, 링크 길이 수정
  server/controller/post-controller.ts
  server/model/entity/Chat.ts
  server/model/entity/Url.ts
  server/routes/post.ts
  server/service/post-service.ts
Labels: backend, fix

#357 fix[#356] : 참여한 공동구매 가져오는 쿼리문 성능 개선
  server/service/participant-service.ts
Labels: backend, fix

#361 bug[#360] : 상세 페이지 제목 버그 수정
  client/src/page/detail/component/Header.tsx
Labels: bug

#359 fix[#358] : 스타일 일부 수정
  client/src/common/chip/index.tsx
  client/src/common/login-modal/index.tsx
  client/src/common/search-modal/component/ButtonSet.tsx
  client/src/page/detail/component/Bottom.tsx
  client/src/page/detail/component/DeadLine.tsx
  client/src/page/detail/component/Header.tsx
  client/src/page/detail/component/LinkPreview.tsx
  client/src/page/detail/index.tsx
  client/src/page/main/component/FAB.tsx
Labels: frontend, fix

#364 게시글 거리를 1km보다 큰 경우 km로 표시
  client/src/common/post-list/component/ItemContent.tsx
Labels: bug, feat, fix

#367 fix[#363] : 서버 꺼진 경우 메인 페이지 예외 처리 및 메인 페이지 게시글 없을 때의 UI 변경
  client/src/asset/noItem.gif
  client/src/asset/noitem.png
  client/src/common/no-post/index.tsx
  client/src/hook/useLoginUser.ts
  client/src/page/main/component/ErrorAlert.tsx
  client/src/page/main/index.tsx
  client/src/page/mypage/component/MyList.tsx
  client/src/page/mypage/component/NoParticipationList.tsx
  client/src/util/error-message.ts
Labels: frontend, fix

#370 스크롤 스타일, 채팅바 아이콘버튼, 채팅바 제목이 긴경우 처리
  client/src/common/back-button/index.tsx
  client/src/common/gnb/index.tsx
  client/src/page/chat/component/ChatBar.tsx
  client/src/page/chat/component/ChatMenuDrawer.tsx
  client/src/style.css
Labels: frontend, fix

#371 fix[#369] : 서치 모달에 SwipeableDrawer 적용
  client/src/common/gnb/component/SearchModalDrawer.tsx
Labels: frontend, fix

#373 fix[#372] : Content 버그 수정
  client/src/page/detail/component/Content.tsx
Labels: frontend, fix

#375 feat[#374] : 사용하지 않는 Wishlist 엔티티 삭제
  server/model/entity/WishList.ts
Labels: backend, feat

#377 fix[#376] : Wishlist 임포트 삭제
  server/model/entity/Post.ts
  server/model/entity/User.ts
Labels: backend, fix

#382 refactor[#381] : 사용하지 않는 Asset 제거 및 Profile 컴포넌트 리팩토링
  client/src/asset/Gugi-Regular.ttf
  client/src/page/mypage/component/Profile.tsx
  client/src/style.css
Labels: frontend, refactor

#385 fix[#384] : 배포 스크립트 수정 및 dependency 수정
  .github/workflows/deploy.yml
  server/package-lock.json
  server/package.json
Labels: backend, fix

#389 fix[#387] : 존재하지 않는 페이지 접속시 에러 페이지 리다이렉트
  client/src/App.tsx
Labels: frontend, fix

#390 상세 페이지 DB에 없는 게시글 조회시 에러 페이지로 리다이렉팅
  server/controller/post-controller.ts
Labels: bug, fix

#392 fix[#391] : 로그인 안된 상태로 마이 페이지 접근시 에러 페이지로 리다이렉트
  client/src/page/mypage/index.tsx
Labels: frontend, fix
